spring:
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/services/customer/**
        - id: vehicle
          uri: lb://vehicle
          predicates:
            - Path=/services/vehicle/**
        - id: rent
          uri: lb://rent
          predicates:
            - Path=/services/rent/**

