server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thamaranga/RentACarApplicationConfigurations
          search-paths:
            - 'service-config/*service'
#This means my config store is local (Configurations are stored  locally.)
#spring:
  #profiles:
    #active: native